name: CI Workflow  # name can be anything

on: # this specifies when will the task will be followed
  push:
    branches:
      - main  # this could be changed according to ur branch name on which you are working
  pull_request:
    branches:
      - main

jobs:
  test:  # test name can be changed to mytest or anything else
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest streamlit

    - name: Run tests
      run: |
        pytest _test.py